spring.application.name=smart_growth_project
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url = jdbc:mysql://localhost:3306/event_collector
spring.datasource.username = root
spring.datasource.password = suren123
spring.jpa.show-sql = true
spring.jpa.hibernate.ddl-auto = update